<div class='container m-auto mt-5 w-50 border p-5 bg-dark text-muted rounded-3'>
<h2>Login</h2>    
<form method="post">
        <div class='form-floating mb-3'>
            <input type="email" class='form-control' placeholder="e" name="email">
            <label>Email</label>
        </div>
        <div class='form-floating mb-3'>
            <input type="password" class='form-control' placeholder="e" name="password">
            <label>Password</label>
        </div>
        <button class="w-100 btn btn-success">Login to <sup>Not</sup>Spotify</button>
    </form>
    <hr>
    <a href='/index/signup'>Create New Account</a>
</div>