<div class='container m-auto mt-5 w-50 border p-5 bg-dark text-muted rounded-3'>
    <form action='/index/auth' method="post">
        <div class='form-floating mb-3'>
            <input type="email" class='form-control' placeholder="e" name="email">
            <label>Email</label>
        </div>
        <button onclick="window.location='/index/auth'" class="w-100 btn btn-success">Login via Spotify</button>
    </form>
</div>